// Config Guard — opencode (mirrors ~/.claude/pi/extensions/config-guard.ts).
// Blocks the model's write/edit/apply_patch and bash tools from mutating the
// derived config dir. the source checkout owns shared config; the config dir is
// regenerated by settings-sync — never hand-edited.
//
// config dir honors $OPENCODE_CONFIG_DIR, else ~/.config/opencode (same env-
// override pattern the superpowers plugin uses; a hardcoded path would miss it).
//
// bash guard is substring + write-signal, not a shell parser:
//  - redirects are target-aware: a read of the dir with stderr to /dev/null (or
//    any redirect whose resolved target isn't the dir) is allowed; only a redirect
//    whose target is the dir blocks. Relative targets resolve against cwd.
//  - ponytail: first-word dispatch misses find -exec / xargs / $() / >(sub).
//    Add if the model uses those to mutate the dir.
// Reads (cat/ls/grep/diff/wc/sed-without-i) stay allowed.
//
// Tool input shapes (from real opencode session records):
//   bash -> { command }   |   write/edit -> { filePath, ... }   (hook reads output.args)
import path from "path"
import os from "os"
import { realpathSync } from "node:fs"
import { fileURLToPath } from "node:url"

const sourceRepo = path.resolve(path.dirname(realpathSync(fileURLToPath(import.meta.url))), "../../..")

const home = os.homedir()
const CONFIG_DIR = (process.env.OPENCODE_CONFIG_DIR && process.env.OPENCODE_CONFIG_DIR.trim())
  ? path.resolve(process.env.OPENCODE_CONFIG_DIR.replace(/^~/, home))
  : path.join(home, ".config", "opencode")

import { bashWritesTo } from "../../../hooks/core/config-policy.mjs"

export const ConfigGuard = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      const tool = input && input.tool
      const args = (output && output.args) || (input && input.args) || {}
      const block = (via, target, extra = "") => {
        throw new Error(
          `BLOCKED: ${target} is a derived target under the opencode config dir (${CONFIG_DIR}), ` +
          `reached via ${via}${extra}. Edit ${sourceRepo}/harnesses/opencode/, then run ` +
          `\`agent-config sync opencode\`. ` +
          `See AGENTS.md config management rules.`,
        )
      }
      if (tool === "edit" || tool === "write" || tool === "apply_patch") {
        const filePath = args.filePath || args.path || ""
        if (filePath) {
          const r = path.resolve(filePath)
          if (r === CONFIG_DIR || r.startsWith(CONFIG_DIR + path.sep)) block(tool, r)
        }
      } else if (tool === "bash") {
        const command = args.command || args.cmd || ""
        if (command && bashWritesTo(command, CONFIG_DIR, home)) {
          block("bash", CONFIG_DIR, ` (command: ${command.length > 100 ? command.slice(0, 97) + "..." : command})`)
        }
      }
    },
  }
}
