"""Tests for scripts/check_skill_graph.py (S1, S4, S5, S11)."""

import importlib.util
import types
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPT = REPO_ROOT / "scripts" / "check_skill_graph.py"

MARKER = "<!-- skill-graph: generated by scripts/check_skill_graph.py - do not edit by hand -->"


@pytest.fixture()
def graph_module() -> types.ModuleType:
    spec = importlib.util.spec_from_file_location("check_skill_graph", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def make_skill(skills_dir: Path, name: str, body: str = "text", deps: list[str] | None = None) -> None:
    d = skills_dir / name
    d.mkdir(parents=True)
    fm = ["---", f"name: {name}", "description: d"]
    if deps is not None:
        fm.append("deps: [" + ", ".join(deps) + "]")
    fm.append("---")
    (d / "SKILL.md").write_text("\n".join(fm) + "\n\n" + body + "\n")


def make_readme(text: str) -> str:
    return f"# Repo\n\nprose with an arrow a --> b outside\n\n{MARKER}\n```mermaid\n{text}\n```\n"


def test_s5_generation_covers_all_nodes_and_edges(graph_module: types.ModuleType, tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    make_skill(skills, "alpha", deps=["beta"])
    make_skill(skills, "beta")
    make_skill(skills, "gamma")
    loaded = graph_module.load_skills(skills)
    body = graph_module.generate_graph(loaded)
    assert body.startswith("flowchart LR")
    for node in ("alpha", "beta", "gamma"):
        assert node.replace("-", "_") in body
    assert "alpha --> beta" in body.replace("_", "-")
    assert body.count("-->") == 1  # edge present exactly once, no invented edges


def test_s1_stale_graph_reports_differing_edges(graph_module: types.ModuleType, tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    make_skill(skills, "alpha", deps=["beta"])
    make_skill(skills, "beta")
    loaded = graph_module.load_skills(skills)
    generated = graph_module.generate_graph(loaded)
    stale = make_readme("flowchart LR\n    alpha\n    beta\n")  # missing alpha --> beta
    diffs = graph_module.compare_block(stale, generated)
    assert any("alpha" in d and "beta" in d for d in diffs)
    assert graph_module.compare_block(make_readme(generated), generated) == []


def test_s11_missing_marker_fails(graph_module: types.ModuleType, tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    make_skill(skills, "alpha")
    loaded = graph_module.load_skills(skills)
    generated = graph_module.generate_graph(loaded)
    readme = "# Repo\n\nno marker anywhere\n"
    with pytest.raises(ValueError, match="marker"):
        graph_module.compare_block(readme, generated)


def test_s4_warn_lint_warns_but_never_fails(graph_module: types.ModuleType, tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    make_skill(skills, "alpha", body="load the grill-me skill first")  # undeclared
    make_skill(skills, "grill-me")
    make_skill(skills, "beta", body="the backlog skill's template")  # no directive verb: no warn
    make_skill(skills, "backlog", body="run beta now", deps=["beta"])  # declared: no warn
    warnings = graph_module.warn_lint(skills, graph_module.load_skills(skills))
    assert any("alpha" in w and "grill-me" in w for w in warnings)
    assert not any("beta" in w for w in warnings)


def test_s1_missing_node_fails(graph_module: types.ModuleType, tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    make_skill(skills, "alpha")
    make_skill(skills, "beta")
    loaded = graph_module.load_skills(skills)
    generated = graph_module.generate_graph(loaded)
    # committed graph dropped beta's node line entirely - edges still match
    stale = make_readme("flowchart LR\n    alpha\n")
    diffs = graph_module.compare_block(stale, generated)
    assert any("missing node" in d and "beta" in d for d in diffs)


def test_write_splice_is_idempotent(graph_module: types.ModuleType) -> None:
    generated = "flowchart LR\n    alpha[alpha]\n"
    once = graph_module.splice_block(make_readme(generated), graph_module.render_block(generated))
    twice = graph_module.splice_block(once, graph_module.render_block(generated))
    assert once == twice


def test_s4_warn_lint_hyphen_sibling_no_false_positive(graph_module: types.ModuleType, tmp_path: Path) -> None:
    skills = tmp_path / "skills"
    # tdd-core is a declared dep; the shorter name tdd must not fire on it
    make_skill(skills, "tdd-core", body="canon")
    make_skill(skills, "tdd", body="canon")
    make_skill(skills, "writer", body="load the tdd-core skill", deps=["tdd-core"])
    warnings = graph_module.warn_lint(skills, graph_module.load_skills(skills))
    assert not any("writer" in w for w in warnings)
