"""Generate the README skill-dependency graph from `deps:` frontmatter and fail
when the committed graph is stale (REQ-SKILLS-11 verification).

`deps:` validity (unknown names, self-references, worker->orchestrator) is
check-skills.py's job; this script generates, compares, and warns. Testable
entry points take (skills_dir, ...); main() resolves the repo root via __file__.
"""

import re
import sys
from pathlib import Path

import yaml

MARKER = "<!-- skill-graph: generated by scripts/check_skill_graph.py - do not edit by hand -->"
DIRECTIVE_VERBS = r"\b(?:invoke|invoking|run|running|load|loading|use|using)\b"


def parse_skill(skill_md: Path) -> tuple[dict, str]:
    text = skill_md.read_text()
    if not text.startswith("---"):
        raise ValueError(f"{skill_md}: missing frontmatter")
    try:
        end = text.index("\n---", 3)
    except ValueError:
        raise ValueError(f"{skill_md}: unterminated frontmatter") from None
    return yaml.safe_load(text[4:end]), text[end + 4 :]


def load_skills(skills_dir: Path) -> dict[str, dict]:
    skills: dict[str, dict] = {}
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        skills[skill_md.parent.name] = parse_skill(skill_md)[0]
    return skills


def _node(name: str) -> str:
    return name.replace("-", "_")


def generate_graph(skills: dict[str, dict]) -> str:
    lines = ["flowchart LR"]
    for name in sorted(skills):
        lines.append(f"    {_node(name)}[{name}]")
    for name in sorted(skills):
        for dep in skills[name].get("deps") or []:
            lines.append(f"    {_node(name)} --> {_node(dep)}")
    return "\n".join(lines)


def _nodes(text: str) -> set[str]:
    labels = {m.group(2) for m in re.finditer(r"^\s*(\w+)\[(.+?)\]$", text, re.M)}
    return {label.replace("_", "-") for label in labels}


def _edges(text: str) -> set[tuple[str, str]]:
    nodes = {m.group(1): m.group(2) for m in re.finditer(r"^\s*(\w+)\[(.+?)\]$", text, re.M)}
    pairs = set()
    for m in re.finditer(r"^\s*(\w+)\s*-->\s*(\w+)\s*$", text, re.M):
        src = nodes.get(m.group(1), m.group(1)).replace("_", "-")
        dst = nodes.get(m.group(2), m.group(2)).replace("_", "-")
        pairs.add((src, dst))
    return pairs


def compare_block(readme_text: str, generated: str) -> list[str]:
    if MARKER not in readme_text:
        raise ValueError(f"README is missing the generated-graph marker line: {MARKER}")
    start = readme_text.index(MARKER)
    fence_start = readme_text.index("```mermaid", start)
    fence_end = readme_text.index("```", fence_start + len("```mermaid"))
    committed = readme_text[fence_start:fence_end]
    diffs = [f"missing node {n}" for n in sorted(_nodes(generated) - _nodes(committed))]
    diffs += [f"stale node {n}" for n in sorted(_nodes(committed) - _nodes(generated))]
    missing = _edges(generated) - _edges(committed)
    stale = _edges(committed) - _edges(generated)
    diffs += [f"missing edge {src} --> {dst}" for src, dst in sorted(missing)]
    diffs += [f"stale edge {src} --> {dst}" for src, dst in sorted(stale)]
    return diffs


def warn_lint(skills_dir: Path, skills: dict[str, dict]) -> list[str]:
    warnings: list[str] = []
    names = sorted(skills)
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        name = skill_md.parent.name
        if skill_md.parent.is_symlink():
            continue  # vendored: never edited, never linted
        deps = set(skills[name].get("deps") or [])
        for line in parse_skill(skill_md)[1].splitlines():
            if not re.search(DIRECTIVE_VERBS, line):
                continue
            for other in names:
                # (?<![A-Za-z0-9-]) ... (?![A-Za-z0-9-]): "tdd" must not match
                # inside "tdd-core" - a declared dep's hyphen-joined sibling
                # is not a mention of the shorter name.
                if other != name and other not in deps and re.search(
                    rf"(?<![A-Za-z0-9-]){re.escape(other)}(?![A-Za-z0-9-])", line
                ):
                    warnings.append(f"{name}: line directs to {other} but {other!r} not in deps")
    return warnings


def render_block(generated: str) -> str:
    return f"{MARKER}\n```mermaid\n{generated}\n```\n"


def splice_block(readme_text: str, block: str) -> str:
    """Replace the marked block in place; append heading + block when absent.

    Idempotent: the block ends with its own closing-fence newline, so the
    splice resumes at the character after that newline (fence_end + 4, the
    three backticks plus their terminator).
    """
    if MARKER in readme_text:
        start = readme_text.index(MARKER)
        fence_end = readme_text.index("```", readme_text.index("```mermaid", start) + 10)
        return readme_text[:start] + block + readme_text[fence_end + 4 :]
    return readme_text.rstrip("\n") + "\n\n## Skill map\n\n" + block


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    skills = load_skills(repo_root / "skills")
    generated = generate_graph(skills)
    readme = repo_root / "README.md"
    readme_text = readme.read_text()
    if "--write" in sys.argv:
        readme_text = splice_block(readme_text, render_block(generated))
        readme.write_text(readme_text)
        print("skill graph: README block regenerated")
    else:
        try:
            diffs = compare_block(readme_text, generated)
        except ValueError as exc:
            print(f"skill graph: {exc}")
            return 1
        for d in diffs:
            print(f"skill graph: {d}")
        if diffs:
            print("skill graph: regenerate with --write (see AGENTS.md rule)")
            return 1
    for w in warn_lint(repo_root / "skills", skills):
        print(f"skill graph (warn): {w}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
