/**
 * Config Guard — pi. Blocks the model's write/edit and bash tools from mutating
 * the derived agent dir. the source checkout owns shared config; the agent dir is
 * regenerated by settings-sync (or, for glm-pi, the launcher) — never hand-edited.
 *
 * Watched dirs (all derived from the source checkout — never hand-edit any of them):
 *   - getAgentDir(): the LIVE dir pi runs against (honors PI_CODING_AGENT_DIR,
 *     else ~/.pi/agent). Under glm-pi this is /tmp/glm-pi-$USER.
 *   - ~/.pi/agent: the default dir that settings-sync populates and the glm-pi
 *     launcher reads from. getAgentDir() does NOT cover this when the live dir is
 *     elsewhere, so a model write to ~/.pi/agent used to sail through; watch it
 *     explicitly. Deduped when both resolve to the same path (plain pi).
 *
 * bash guard is substring + write-signal, not a shell parser:
 *  - redirects are target-aware: a read of the dir with stderr to /dev/null (or
 *    any redirect whose resolved target isn't the dir) is allowed; only a redirect
 *    whose target is the dir blocks. Relative targets resolve against cwd.
 *  - ponytail: first-word dispatch misses find -exec / xargs / $() / >(sub).
 *    Add if the model uses those to mutate the dir.
 * Reads (cat/ls/grep/diff/wc/sed-without-i) stay allowed.
 *
 * Only intercepts the MODEL's tool_call. pi's own writes (auth.json,
 * lastChangelogVersion, sessions) don't fire tool_call, so blocking the whole
 * dir can't break them.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { getAgentDir } from "@earendil-works/pi-coding-agent";
import path from "node:path";
import os from "node:os";
import { realpathSync } from "node:fs";
import { fileURLToPath } from "node:url";

const sourceRepo = path.resolve(path.dirname(realpathSync(fileURLToPath(import.meta.url))), "../../..");

import { bashWritesTo } from "../../../hooks/core/config-policy.mjs";

export default function (pi: ExtensionAPI) {
  const home = os.homedir();
  const liveDir = getAgentDir();
  const defaultDir = path.join(home, ".pi", "agent");
  // Dedupe (plain pi: both resolve to ~/.pi/agent).
  const protectedDirs = Array.from(new Set([liveDir, defaultDir].map((d) => path.resolve(d))));

  const underDir = (r: string): string | undefined =>
    protectedDirs.find((d) => r === d || r.startsWith(d + path.sep));

  const reason = (via: string, target: string, dir: string, extra = "") =>
    `BLOCKED: ${target} is a derived target under the pi agent dir (${dir}), reached via ${via}${extra}. ` +
    `Edit ${sourceRepo}/harnesses/pi/ (or the launcher), then run agent-config sync pi and re-launch. See ${sourceRepo}/harnesses/pi/README.md.`;

  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName === "write" || event.toolName === "edit") {
      const raw = (event.input as { path?: string } | undefined)?.path;
      if (raw) {
        const r = path.resolve(raw.replace(/^~/, home));
        const dir = underDir(r);
        if (dir) {
          if (ctx.hasUI) ctx.ui.notify(`Blocked ${event.toolName} to derived path: ${r}`, "warning");
          return { block: true, reason: reason(event.toolName, r, dir) };
        }
      }
    } else if (event.toolName === "bash") {
      const command = (event.input as { command?: string } | undefined)?.command;
      if (command) {
        const dir = protectedDirs.find((d) => bashWritesTo(command, d, home));
        if (dir) {
          if (ctx.hasUI) ctx.ui.notify(`Blocked bash write to derived path: ${dir}`, "warning");
          const snip = command.length > 100 ? command.slice(0, 97) + "..." : command;
          return { block: true, reason: reason("bash", dir, dir, ` (command: ${snip})`) };
        }
      }
    }
    return undefined;
  });
}
